Add UI refinements to prepare for 1.0 release.
gravityforms/gravityformsakismet pull request #3
Opened 2021-06-24 14:53 UTC by jmichaelward

2021-06-24 15:11 UTC, jmichaelward commented
@speerface - FYI, I've assigned you as a reviewer to this PR to provide copywriting feedback.

2021-06-24 15:21 UTC, jmichaelward commented
> I'd also test the property name. It's unlikely but it is possible someone could store a value of spam in one of the other entry properties. An alternative approach would be to use the property specific action `gform_update_status` instead.

Thanks, @richardW8k. I've updated this.

2021-06-24 15:21 UTC, speerface requested changes
A couple very-small notes about the copy, one of which (the grammar note) should be addressed one way or another, and the others which are really more just thoughts than requested changes.

2021-06-24 15:21 UTC, speerface commented on includes/settings/class-form-settings.php
> +			'description'   => esc_html__( 'Untoggle this option to deactivate Gravity Forms Akismet spam controls for this form.', 'gravityformsakismet' ),
The only thing here that I'm not sure about is "Untoggle". For me, a developer who knows this input type is "toggle", it makes sense, but I'm not entirely convinced that all our customers will know what that means. I wonder if something more generic like "Turn off this option" or "Disable this option" would be more universal here?

2021-06-24 15:21 UTC, speerface commented on class-gf-akismet-enhancements.php
> +			$errors[]           = esc_html__( 'The Akismet plugin is either not currently installed or it is inactive.', 'gravityformsakismet' );
If my grammar memory is accurate, we either need a comma after `installed`, or remove `it` from the second half of the sentence:

> The Akismet plugin is either not currently installed, or it is inactive.

or

> The Akismet plugin is either not currently installed or is inactive.

2021-06-24 15:21 UTC, speerface commented on includes/settings/class-form-settings.php
> +				'description' => esc_html__( 'Uncheck this option to deactivate Gravity Forms Akismet spam controls for this form.', 'gravityformsakismet' ),
In general we've tried to prioritize brevity in our messaging to avoid long chunks of text. I think this is great as-is, but we might consider just saying "Akismet" here instead of "Gravity Forms Akismet". If we feel that'll confuse customers about Akismet vs. Gravity Forms Akismet, that's reasonable, but I just wanted to toss it out there!

2021-06-24 15:24 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +				'description' => esc_html__( 'Uncheck this option to deactivate Gravity Forms Akismet spam controls for this form.', 'gravityformsakismet' ),
I think that makes sense. I am concerned about the distinction and potential for confusion: disabling this setting but leaving Akismet activated on the site means Akismet might still mark an entry as spam. That said, I might need more clarification from @richardW8k, because it's possible the intent here is to prevent Akismet _itself_ from marking anything as spam, as well? 

I also just now realized in either case that I'll need to update my note method to check whether this method is activate for the given form.

2021-06-24 15:26 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +			'description'   => esc_html__( 'Untoggle this option to deactivate Gravity Forms Akismet spam controls for this form.', 'gravityformsakismet' ),
Changed to disabled. Your feedback about "Gravity Forms Akismet" will be applicable here, too, so I'll await feedback from @richardW8k about the intent of the control.

2021-06-24 15:29 UTC, jmichaelward commented on class-gf-akismet-enhancements.php
> +			$errors[]           = esc_html__( 'The Akismet plugin is either not currently installed or it is inactive.', 'gravityformsakismet' );
I changed this to `The Akismet plugin is either inactivate or not installed.`

2021-06-24 15:40 UTC, speerface approved these changes

2021-06-24 19:29 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +				'description' => esc_html__( 'Uncheck this option to deactivate Gravity Forms Akismet spam controls for this form.', 'gravityformsakismet' ),
Sounds like the intent here is that the filter only runs when Akismet is enabled to check for spam, and disabling this option disables the Akismet check for the form as well, so both cases of this description text should simply say Akismet. I've updated the text.

I'm also going to move these into tooltips, I think.

2021-06-24 21:02 UTC, jmichaelward commented
@adampickering Just noting @michelle-bauer's feedback in #4: https://github.com/gravityforms/gravityformsakismet/pull/4#issuecomment-867946254. 

This add-on doesn't have a stylesheet, so we may want to examine whether there are any RTL issues in core that are affecting the presentation of the form settings page and open a separate issue if that's the case.

2021-06-25 02:44 UTC, michelle-bauer requested changes
Here are the issues I noted:

1. I am not seeing the "missing requirements" notification on the Settings page when Akismet is toggled off. The notice does appear on the form pages.

2. The time for the marked as spam note is using universal time and not the site's set time.

3. When viewing the log data, I am seeing the source url merge tag data instead of the actual value: 
`[comment_author_url] => source_url`

4. For test step 12 I am not seeing a way to manually mark the entry as spam when Akismet is disabled for the form.

I recorded a video to help detail what I am seeing: https://www.loom.com/share/ec679c69f03540fcb432f58c66a403f7

2021-06-25 08:24 UTC, richardW8k requested changes

2021-06-25 08:24 UTC, richardW8k commented on includes/settings/class-form-settings.php
> +								'field_type' => array( 'website', 'text', 'hidden' ),
seems like the `field_type` restrictions aren't being applied i'm seeing other field types and entry properties in the form field drop downs

2021-06-25 08:24 UTC, richardW8k commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
I just realized the submission time call to `GFFormsModel::update_entry_property()` to set the spam status passes `true` for the `$disable_hook` arg so the note won't be added during submission. If we want to add a note when Akismet marks the submission as spam we'll need to do it from `http_api_debug()` based on the response body.

2021-06-25 08:34 UTC, richardW8k commented on akismet.php
>  Description: This add-on is for testing possible enhancements to the Gravity Forms Akismet integration.
Description needs an update

2021-06-25 10:22 UTC, adampickering commented
I think we could improve the UI in the following ways.

- Checkbox to a Toggle and refine the message that is displayed. 
- Change the author details section to remove the title of the section and display each input full-width without the field / form field sections.
- Eventually not in this PR we have plans to re-design the merge tags UI/Drop-down so please disregard that in this PR/Screenshot.

Update the <img width="794" alt="CleanShot 2021-06-25 at 06 19 16@2x" src="https://user-images.githubusercontent.com/746776/123410441-580ff080-d57d-11eb-8cd0-d9ee2c72c269.png">

2021-06-25 15:45 UTC, jmichaelward commented
> Here are the issues I noted:
> 
>     1. I am not seeing the "missing requirements" notification on the Settings page when Akismet is toggled off. The notice does appear on the form pages.
> 
>     2. The time for the marked as spam note is using universal time and not the site's set time.
> 
>     3. When viewing the log data, I am seeing the source url merge tag data instead of the actual value:
>        `[comment_author_url] => source_url`
> 
>     4. For test step 12 I am not seeing a way to manually mark the entry as spam when Akismet is disabled for the form.
> 
> 
> I recorded a video to help detail what I am seeing: https://www.loom.com/share/ec679c69f03540fcb432f58c66a403f7

Thanks @michelle-bauer. I'll get items 2 and 3 fixed and re-request your review once they're ready.

For item 1, I'd forgotten that the "missing requirements" notice only shows on particular pages of the admin, and weirdly, the Settings page is not one of them. I think I'm going to open a separate issue to look at this in core, because our missing requirements flow is really inconsistent right now - we run some add-on processes even after the requirements check fails (see gravityforms/backlog#1196), and as you've seen, the notice doesn't show on every Gravity Forms page.

For item 4, I'm not sure what the cause is, but I noticed in your video that Mark as Spam also wasn't available when you had Akismet active and enabled, too. Maybe @richardW8k has a bit more insight as to when that option gets displayed? Do you have Akismet configured with a key?

2021-06-25 15:47 UTC, jmichaelward commented on akismet.php
>  Description: This add-on is for testing possible enhancements to the Gravity Forms Akismet integration.
I thought the same, but didn't really know how to describe the add-on. :D Any suggestions on what it should be?

2021-06-25 15:48 UTC, jmichaelward commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
Thanks for catching this - I think the `http_api_debug` callback seems like the best time to do it. I'll dig into that and get it updated for you before re-review.

2021-06-25 15:51 UTC, jmichaelward commented on class-gf-akismet.php
> +			gmdate( 'H:i:s' )
I wasn't sure exactly how this time worked since it's relative and didn't have a point of reference for an older note, but yes, if it's already there then we should absolutely remove this. It will help resolve the UTC time issue Michelle identified, as well.

2021-06-25 15:52 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +				'author'  => empty( $akismet_fields['comment_author_first_name'] ) || empty( $akismet_fields['comment_author_last_name'] ),
Good catch. I mentally flagged this when I created it and realize now that I never circled back. Assuming then that this should be an `and` since we concatenate if a name field is found anyway?

2021-06-25 15:52 UTC, richardW8k commented
@jmichaelward @michelle-bauer the mark as spam link should be displayed if the Akismet integration is enabled for the form or if the gform_entry_is_spam filter is in use by another active plugin e.g. GravityView Zero Spam or our new reCAPTCHA add-on

2021-06-25 15:54 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +								'field_type' => array( 'website', 'text', 'hidden' ),
I may need some help in understanding better how field maps work. Do we have any more documentation about them on gravityforms.com? I was looking at the Field Map example in the settings API and based this on what's there.

Is this possibly a bug in core?

2021-06-25 16:02 UTC, jmichaelward commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
I moved this filter into `http_api_debug`.

2021-06-25 16:03 UTC, jmichaelward commented on class-gf-akismet.php
> +			gmdate( 'H:i:s' )
I updated the text to read `This entry has been marked as spam`. cc: @speerface - does that simplified verbiage work for you, too?

2021-06-25 16:04 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +				'author'  => empty( $akismet_fields['comment_author_first_name'] ) || empty( $akismet_fields['comment_author_last_name'] ),
Changed to `&&`. Think I'll write a test for this scenario, too.

2021-06-25 16:09 UTC, jmichaelward commented
@adampickering and I had a call this morning and agreed that the settings UI as it stands is fine for now and that we shouldn't be making any changes to the presentation of the fields included in this add-on. We instead agreed to open a set of issues to address some of the settings API issues, such as rethinking how generic field maps are presented, adding an option for a label next to a toggle (separate from the actual label itself, which is used as text on top of the toggle), making sure the `class` options of `small`, `medium`, and `large` can be used to resize inputs, etc.

We also discussed the idea of developing an add-on which registers all of the different field types for the settings API in each of the plugin, form, and feed settings, so that the core team can use it as a visual point of reference when making style adjustments.

Finally, we updated the verbiage of the toggle - @speerface, I've flagged you for re-review so you can approve the updated text once more.

2021-06-25 16:10 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +			'label'         => esc_html__( "Enable to protect this form's entries from spam using Akismet", 'gravityformsakismet' ),
@speerface Let me know if this revised text works for you - this shows up as the label above the toggle. It's longer than before, but is inline with @adampickering's design mockups.

2021-06-25 16:11 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +				'description' => esc_html__( "Enable to protect this form's entries from spam using Akismet", 'gravityformsakismet' ),
@speerface This is the same text as line 130, but we set it as a description so that it appears beneath the checkbox in 2.4, as including it as a label would make the text wrap far too much. We opted for `Akismet enabled` as the label in this case.

2021-06-25 16:17 UTC, speerface commented on includes/settings/class-form-settings.php
> +			'label'         => esc_html__( "Enable to protect this form's entries from spam using Akismet", 'gravityformsakismet' ),
`Enable to protect` feels a little cumbersome to me, but I can't quite put my finger on why (or think of a good alternative), so I think this should work! Overall it's nice and clear, so that's awesome!

2021-06-25 16:18 UTC, speerface commented on includes/settings/class-form-settings.php
> +				'description' => esc_html__( "Enable to protect this form's entries from spam using Akismet", 'gravityformsakismet' ),
This is mostly just my ignorance of how Translationpress works, but do we know if having the same string twice will appear as a single string to translate, or if it'll show up as two different strings to translate? If the latter, I could see that being odd, so maybe we make this a variable/method we can call to get the verbiage? (Or if it's not an issue at all, disregard)

2021-06-25 16:22 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +				'description' => esc_html__( "Enable to protect this form's entries from spam using Akismet", 'gravityformsakismet' ),
I don't know the answer, but I don't think there's any harm in capturing the repeated string in a variable. I'll update. Thanks!

2021-06-25 16:24 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +				'description' => esc_html__( "Enable to protect this form's entries from spam using Akismet", 'gravityformsakismet' ),
Another interesting wrinkle is that TranslationsPress is only available in 2.5, right? So I'm not even entirely clear on how translations get added for 2.4.

All told, I still think this is a good change and I've updated it.

2021-06-25 16:33 UTC, adampickering approved these changes
Many of the issues that I have pointed out will be solved in other issues. i.e. 

https://github.com/gravityforms/backlog/issues/1625

Approved

2021-06-25 20:30 UTC, jmichaelward commented
@michelle-bauer This is ready for you to give another look. `source_url` now gets mapped if you use it, along with any of the other entry properties. My _hunch_ is that we may want to exclude some of the values that are showing up in the field map, and I think @richardW8k and I may be identifying some improvements that need to happen in the Generic_Map class in core to get this to be exactly the way we need, but I think he and I will need to reconnect about that on Monday.

2021-06-25 20:35 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +			switch ( $value ) {
@richardW8k This is my new approach for mapping settings values to parsed values. I think it's still not quite right, but it addresses the issue Michelle raised about `source_url` not getting parsed.

Essentially:
- If we have a field, get the value.
- If we have a merge tag, get the value.
- If we have an entry array key, get its value.
- Otherwise, do nothing.

I realized, too, that `$mapped_value` for name returns the full name, so I think I still need to resolve something around name normalization, because the names will actually get concatenated. We need more tests.

2021-06-25 21:33 UTC, michelle-bauer approved these changes
> > Here are the issues I noted:
> > ```
> > 1. I am not seeing the "missing requirements" notification on the Settings page when Akismet is toggled off. The notice does appear on the form pages.
> > 
> > 2. The time for the marked as spam note is using universal time and not the site's set time.
> > 
> > 3. When viewing the log data, I am seeing the source url merge tag data instead of the actual value:
> >    `[comment_author_url] => source_url`
> > 
> > 4. For test step 12 I am not seeing a way to manually mark the entry as spam when Akismet is disabled for the form.
> > ```
> > I recorded a video to help detail what I am seeing: https://www.loom.com/share/ec679c69f03540fcb432f58c66a403f7
> 
> Thanks @michelle-bauer. I'll get items 2 and 3 fixed and re-request your review once they're ready.
> 
> For item 1, I'd forgotten that the "missing requirements" notice only shows on particular pages of the admin, and weirdly, the Settings page is not one of them. I think I'm going to open a separate issue to look at this in core, because our missing requirements flow is really inconsistent right now - we run some add-on processes even after the requirements check fails (see [gravityforms/backlog#1196](https://github.com/gravityforms/backlog/issues/1196)), and as you've seen, the notice doesn't show on every Gravity Forms page.
> 
> For item 4, I'm not sure what the cause is, but I noticed in your video that Mark as Spam also wasn't available when you had Akismet active and enabled, too. Maybe @richardW8k has a bit more insight as to when that option gets displayed? Do you have Akismet configured with a key?

1. Understood
2. Resolved
3. Resolved
4. I am only not seeing the Mark as Spam link when Akismet is disabled for the form (yes, I have it set up with a key).  I believe this is the expected behavior based on what Richard said.

2021-06-25 21:56 UTC, jmichaelward commented
Thanks, Michelle. I think I understand better about the "mark as spam" thing now between testing and Richard's comments. I made a little video that demonstrates: https://d.pr/v/HRDGr0

Richard's right that if another plugin is installed that enables spam filters, the link will be displayed even if the Akismet integration is disabled.

2021-06-28 08:57 UTC, richardW8k requested changes

2021-06-28 08:57 UTC, richardW8k commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
The note still wasn’t added. I think we need to change hooks e.g.

```
if ( rgar( $simplified_response, 1 ) === 'true' ) {
	add_action( 'gform_entry_created', array( $this, 'add_marked_as_spam_note_to_entry' ) );
}
```

In which case `add_marked_as_spam_note_to_entry` would change to something like this:
```
public function add_marked_as_spam_note_to_entry( $entry ) {
	if ( rgar( $entry, 'status' ) !== 'spam' ) {
		return;
	}

	$this->add_note( rgar( $entry, 'id' ), esc_html__( 'This entry has been marked as spam.', 'gravityformsakismet' ), 'success' );
}
```

2021-06-28 08:57 UTC, richardW8k commented on class-gf-akismet-enhancements.php
> -<?php
this empty file can be deleted

2021-06-28 08:57 UTC, richardW8k commented on class-gf-akismet.php
> +		'gravityforms_gravityformsakismet_uninstall',
Looks like I forgot to fix the caps issue when I first created the add-on. I have an [open PR to fix it in the generator](gravityforms/gravityformsaddongenerator/pull/3).

```suggestion
		'gravityforms_akismet',
		'gravityforms_akismet_uninstall',
```

2021-06-28 08:57 UTC, richardW8k commented on class-gf-akismet.php
> +	protected $_capabilities_settings_page = 'gravityforms_gravityformsakismet';
```suggestion
	protected $_capabilities_settings_page = 'gravityforms_akismet';
```

2021-06-28 08:57 UTC, richardW8k commented on class-gf-akismet.php
> +	protected $_capabilities_form_settings = 'gravityforms_gravityformsakismet';
```suggestion
	protected $_capabilities_form_settings = 'gravityforms_akismet';
```

2021-06-28 08:57 UTC, richardW8k commented on class-gf-akismet.php
> +	protected $_capabilities_uninstall = 'gravityforms_gravityformsakismet_uninstall';
```suggestion
	protected $_capabilities_uninstall = 'gravityforms_akismet_uninstall';
```

2021-06-28 08:57 UTC, richardW8k commented on akismet.php
>  Description: This add-on is for testing possible enhancements to the Gravity Forms Akismet integration.
I bow to the wordsmithing might of @speerface but my suggestion would be along the lines of 
> Enhance Gravity Forms with advanced spam protection by Akismet.

2021-06-28 08:57 UTC, richardW8k commented on includes/class-akismet-fields-filter.php
> +				'author'  => empty( $akismet_fields['comment_author_first_name'] ) && empty( $akismet_fields['comment_author_last_name'] ),
I'm now wondering if the first and last name fields should be checked at all. Hasn't `normalize_field_data()` already taken care of merging them into `comment_author`?

2021-06-28 08:57 UTC, richardW8k commented on includes/settings/class-form-settings.php
> +								'field_type' => array( 'website', 'text', 'hidden' ),
Docs for the field_map setting can be found at https://docs.gravityforms.com/field_map-field/ but it's outdated. It does look like there is an issue with the new settings classes for `Field_Map` or `Generic_Map`, not taking into consideration the specified types when calling `get_value_choices()`. I'm not sure how to resolve it though as it also seems like it currently expects to use the same choices for all the mappings which wasn't the case with 2.4 and earlier.

2021-06-28 13:20 UTC, richardW8k commented on includes/settings/class-form-settings.php
> +								'field_type' => array( 'website', 'text', 'hidden' ),
Confirmed this field map issue is also impacting other add-ons so I've opened gravityforms/backlog/issues/1627

2021-06-28 13:23 UTC, jmichaelward commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
@richardW8k Can you provide replication instructions for when the note isn't getting added?

2021-06-28 13:26 UTC, richardW8k commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
I submitted a form with akismet-guaranteed-spam@example.com in the email field and then viewed the entry detail page to find the note wasn't there.

2021-06-28 13:26 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +			switch ( $value ) {
Hmm. Can you provide me replication instructions for this, as well? I want to understand why the switch condition on line 195 is passing (field is an instance of the GF_Field class), but then field is suddenly a boolean on line 196. Something sounds off.

2021-06-28 13:30 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +				'author'  => empty( $akismet_fields['comment_author_first_name'] ) && empty( $akismet_fields['comment_author_last_name'] ),
That's correct – `normalize_field_data` takes any oddball fields (in this case, it's currently only the name), and applies it to our initial akismet field data. If the name field is empty, however, `comment_author` will be empty, and `set_missing_keys` will let us know that the author is missing and that we need to check another field.

I think this section of the code is maybe a little trickier to follow, so I might need to make some adjustments to the algorithm in the public method to make it clearer, and perhaps come up with a better name for `normalize_field_data`.

2021-06-28 13:34 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +								'field_type' => array( 'website', 'text', 'hidden' ),
I've updated that issue with a link back to this conversation to provide context around any documentation updates that might be needed. @richardW8k is there anything else I can or should do here right now?

2021-06-28 13:36 UTC, jmichaelward commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
Thank you - I can confirm I see the same thing. I'll get this updated.

2021-06-28 13:41 UTC, richardW8k commented on includes/class-akismet-fields-filter.php
> +			switch ( $value ) {
I've mapped all the settings except the content: 
![Screenshot 2021-06-28 at 14 36 59](https://user-images.githubusercontent.com/1872371/123645648-6a5c8980-d81e-11eb-9f0d-0dc3595e9230.png)
Submitting with akismet-guaranteed-spam@example.com in the email field the fatal error occurs.

The error appears to be occuring when it is processing comment_content which doesn't have a value.

2021-06-28 14:01 UTC, jmichaelward commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
Hmm. Weirdly, I'm not seeing `filter_akismet_fields` getting called. There's nothing in the logs, and I can't trigger an Xdebug breakpoint, but I am able to do so in other methods, such as `filter_akismet_enabled`. I'm going to have to dig into this some more before making this change; there might be something else going on.

2021-06-28 14:06 UTC, richardW8k commented on class-gf-akismet.php
> +		add_filter( 'gform_update_status', array( $this, 'add_marked_as_spam_note_to_entry' ), 10, 3 );
Is the Akismet API configured in the site settings? I removed the key from my test site while testing last week, it took me a while to figure out that was why submissions weren't being processed when i started testing again this morning.

2021-06-28 14:47 UTC, jmichaelward commented on class-gf-akismet.php
> +	public function handle_akismet_response( $response, $context, $class, $args, $url ) {
@richardW8k I've made a few changes here to address the "mark as spam" issue, but to also hopefully make things a little easier to follow for us all by extracting some of the complex conditionals into named methods.

Take a look and let me know what you think. I was able to replicate your spam instructions using the test e-mail you provided, and this should now work in both cases, but of course will no longer add a note if the entry is marked as spam from the admin. Not sure whether we still need that or not, but if we do, perhaps we can add the other filter back into the `maybe_mark_as_spam` method.

2021-06-28 14:47 UTC, jmichaelward commented on class-gf-akismet.php
> +		return (
I took the complex conditional from what was previously `http_api_debug` and inverted it here so that we're explicitly stating that something is a response we want to handle.

2021-06-28 14:48 UTC, jmichaelward commented on class-gf-akismet.php
> +		$this->log_debug( __METHOD__ . '(): marking entry as spam.' );
I thought we might want to log when we're marking something as spam, as well.

2021-06-28 14:49 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +			switch ( $value ) {
Thanks - I'm able to replicate. I'll dig into this a bit more and consider an alternate approach.

2021-06-28 15:49 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +			switch ( $value ) {
@richardW8k I've reverted back to a version of what you're proposing, choosing instead to extract the functionality into a separate method so we can document the logic that's happening there.

Looking more closely at `get_field_value`in the add-on, I can understand why I went back and forth on this approach. I believe I was trying to use this originally, but moved to the GF_Field `get_value_export` method instead because it seemed to be more explicit. Once Michelle left her feedback about `source_url`, I created a workaround to try and get the entry properties, without realizing that `get_field_value` does that automatically. I think I was unclear that `$field_id` might represent something that's not an actual field, so I wonder whether there are opportunities for more explicit documentation on the `get_field_value` method within core - that method is doing a lot more than I expected.

2021-06-28 16:06 UTC, jmichaelward commented on includes/class-akismet-fields-filter.php
> +				'author'  => empty( $akismet_fields['comment_author_first_name'] ) && empty( $akismet_fields['comment_author_last_name'] ),
Hmm, nope, dug into this some more, and it looks like you're right again. I think I'd set this in place before I created the normalize method, and so yes, `comment_author` is what we should be checking. I realized the populate fallback method was getting called every time, and reverting this back to `comment_author` fixes it. Great catch.

2021-06-28 16:09 UTC, jmichaelward commented on akismet.php
>  Description: This add-on is for testing possible enhancements to the Gravity Forms Akismet integration.
How about `Enhance Gravity Forms with advanced spam protection, powered by Akismet.`? 

@speerface Any ideas?

2021-06-28 18:17 UTC, sswebster reviewed
This is looking great to me and everything works! The only thing I noticed is that I'm not getting a note that says the entry was marked as spam if I manually do so. It looks I should be from the testing instructions, but I'm not sure if that's the case since in that situation Akismet wouldn't actually be doing anything, so it would be a little odd for it to generate a note.

I do successfully get the message when Akismet marks something as spam. Is this an issue that needs to be resolved?

2021-06-28 20:01 UTC, jmichaelward commented
Thanks, @sswebster. I think I need to update the testing instructions a bit now since things have shifted around a little. @richardW8k and I went back and forth about adding the note, and there's not a separate method `maybe_mark_as_spam` that sets the filters in various scenarios. We switched to the `gform_entry_created` hook instead of `gform_update_status`, so the note will only get added at the time the entry is created. 

I do think there's some room for discussion whether we should also add a note when the entry gets updated in the admin, as it was before, but seeing how that's not strictly an Akismet event, it might make sense to only do it at the time that Akismet identifies spam. What do you think?

2021-06-28 20:11 UTC, richardW8k commented
The spam/not spam links can appear when any anti-spam integration is active so I don't think the add-on should add the notes when those links are used. I think core should handle adding user notes which identify the user that performed the action.

2021-06-28 20:40 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +								'field_type' => array( 'website', 'text', 'hidden' ),
Just to have a document of it, I've created a branch off this one that uses the `field_select` type instead of `field_map`, which should resolve this issue. Once I hear back from @adampickering as to his preference, I'll either merge that change into this branch, or I'll close out that branch in favor of moving forward with this as-is.

2021-06-29 01:01 UTC, sswebster commented
I agree with @richardW8k here, I don't think Akismet should be responsible for adding spam notes unless it's the one marking things as spam. So given that, I'll go ahead and approve this

2021-06-29 01:01 UTC, sswebster approved these changes

2021-06-29 13:49 UTC, richardW8k requested changes
The settings just need a little more work to resolve the issue with the drop downs listing all fields and then this is good to merge.

2021-06-29 13:49 UTC, richardW8k commented on includes/settings/class-form-settings.php
> +						'field_type' => array( 'name', 'text', 'hidden' ),
For these `field_select` fields the `field_type` properties all need changing to `args` which is an array with the array of types assigned to the `input_types` property e.g.

```
'args' => array(
	'input_types' => array( 'name', 'text', 'hidden' ),
),
```

2021-06-29 13:55 UTC, adampickering commented
Hey @speerface Have you been asked to wordsmith this yet? If not could you?

<img width="379" alt="CleanShot 2021-06-29 at 09 55 12@2x" src="https://user-images.githubusercontent.com/746776/123810051-1c985d80-d8c0-11eb-9c8c-44e4b44d5509.png">

2021-06-29 14:01 UTC, jmichaelward commented on includes/settings/class-form-settings.php
> +						'field_type' => array( 'name', 'text', 'hidden' ),
This is changed, and I see the difference in the UI now. Thank you.

2021-06-29 15:14 UTC, richardW8k approved these changes

2021-06-29 15:19 UTC, merged

2021-07-01 18:07 UTC, juzzyp commented
Operational question here for you @jmichaelward : 

Previously our docs specified that "You can add multiple merge tags for a field by separating them with a comma.". Is the comma still required, or will it create a concatenated field to pass no matter what you add between merge tags.  E.g. {fieldA} -- {fieldB} ?

2021-07-01 18:09 UTC, jmichaelward commented
Hey @juzzyp! Good question. First, note that the name, e-mail, and website fields are no longer text fields and the corresponding field must be selected from a dropdown. For the remaining text fields, I defer to @richardW8k, since he'd developed it originally. My understanding is that any concatenation will work, but he can confirm that.

2021-07-01 18:21 UTC, juzzyp commented
> @juzzyp are you sure that's from Akismet related docs? it sounds more like it's from the docs for a mailing list add-on in relation to a tags field which requires the comma to be used so it can convert the value to the array required by the API.
> 
> are you sure that's from Akismet related docs? it sounds more like it's from the docs for a mailing list add-on in relation 
to a tags field which requires the comma to be used so it can convert the value to the array required by the API.

I cannot be sure, it was a draft J.Smith put together yesterday, I am rewriting it and checking. I will ignore it. 

> The Akismet subject and content fields accept any combination of text and merge tags, no special characters required. They are more like notification settings.

Great.

2021-07-01 18:23 UTC, juzzyp commented
@richardW8k 

Are the form fields and merge tags listed in the mapping screenshot above the **actual defaults**? (what is the default for Content? Any paragraph field? )

And if yes, are there fallbacks if you don't have that on your form? (e.g. what if no first name & last name, just a username, or one of them turned off)?

2021-07-01 18:51 UTC, richardW8k commented
@juzzyp the field selects will try to default to the first field of the matching type. The subject setting defaults to `{form_title}` and the content setting will attempt to default to the merge tag for a paragraph or post content field.

Submission time fallbacks for empty fields when the mappings/merge tags are processed remain as documented in the repo readme

2021-07-06 13:37 UTC, juzzyp commented
@richardW8k Can you clarify how that behavior works with the README note that: 

> The values contained in the following field types will be sent as the content if needed: address, email, hidden, list, name, number, phone, post_content, post_excerpt, post_tags, post_title, text, textarea, website

Is this just saying that these are the "matching types"?

2021-07-06 13:41 UTC, richardW8k commented
@juzzyp the values of those field types, as long as they aren't set as administrative, will be sent to Akismet if the content setting is empty or the merge tags found in that setting return empty when the entry is processed.